version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: imovel-guide-api
    working_dir: /var/www
    volumes:
      - ../laravel:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: imovel-guide-webserver
    volumes:
      - ../laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: imovelguide-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imovelguide
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
